// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
export interface Env {
  TO_EMAIL: string;
  FROM_EMAIL: string;
  RESEND_KEY: string;
}
